#+TITLE: emacs configuration
#+author: kang
#+startup: overview

* Welcome!

This is the configuration we've been building in the *Emacs From Scratch* series, now written as an Org Mode document.  This file generates [[file:init.el][init.el]] which can be loaded by Emacs at startup.

*NOTE:* If you run into any issues while using this configuration, please [[https://github.com/daviwil/emacs-from-scratch/issues/new][file an issue]] or send me an email at =david at systemcrafters.cc=.

The following variables are used to tweak some of the configuration pieces for use in the live streams so you might need to adjust them for your local machine if you try to use this configuration directly.

#+begin_src emacs-lisp

  ;; NOTE: init.el is now generated from Emacs.org.  Please edit that file
  ;;       in Emacs and init.el will be generated automatically!

  ;; You will most likely need to adjust this font size for your system!
  (defvar psk/default-font-size 105)
  (defvar psk/default-variable-font-size 105)
  (defvar kps/default-projectile-path "~/ext/WORKSPACE/")
  (defvar psk/task_file_path "~/DOCS/Tasks.org")
  (defvar psk/habit_file_path "~/DOCS/Habits.org")
  (defvar psk/birthday_file_path "~/DOCS/Birthday.org")

  ;; Make frame transparency overridable
  (defvar efs/frame-transparency '(95 . 90))
  (defvar backup-directory "~/.backups")

  (fset 'yes-or-no-p 'y-or-n-p)

  ;;  (define-key global-map (kbd "C->") 'text-scale-increase)
  ;;  (define-key global-map (kbd "C-<") 'text-scale-decrease)
  (global-set-key [C-iso-lefttab] 'previous-buffer)
  (global-set-key [C-tab] 'next-buffer)
  (global-set-key (kbd "<f5>") 'revert-buffer)
  (global-set-key (kbd "<f4>") 'goto-linez)
  (global-set-key [f7] 'comment-region)
  (global-set-key [f8] 'uncomment-region)
  (global-set-key (kbd "<f11>") 'highlight-symbol-at-point)
  (global-set-key [f9] 'bookmark-set)
  (global-set-key (kbd "C-c h o") 'occur)
  (global-set-key (kbd "C-c h r") 'rgrep)

  ;;(global-set-key [f12] 'bookmark-bmenu-list)
  ;;(global-set-key [f12] 'imenu-list-smart-toggle)

  (add-to-list 'auto-mode-alist '("\\Make.defs\\'" . makefile-mode))
  (add-to-list 'auto-mode-alist '("SConstruct" . python-mode))

#+end_src

** Environment configuration
*** Linux
#+BEGIN_SRC emacs-lisp
  (when (eq system-type 'gnu/linux)
    (let ((pscript-path "/home/pillip/UTILS/coding_rule"))
      (add-to-list 'exec-path pscript-path)
      (setenv "PATH" (concat pscript-path path-separator (getenv "PATH")))))
#+END_SRC

* Startup Performance


#+begin_src emacs-lisp

  ;; The default is 800 kilobytes.  Measured in bytes.
  (setq gc-cons-threshold (* 50 1000 1000))

  (defun efs/display-startup-time ()
    (message "Emacs loaded in %s with %d garbage collections."
             (format "%.2f seconds"
                     (float-time
                      (time-subtract after-init-time before-init-time)))
             gcs-done))

  (add-hook 'emacs-startup-hook #'efs/display-startup-time)

  ;; Increase the amount of data which Emacs reads from the process. Again the emacs default is too
  ;; low 4k considering that the some of the language server responses are in 800k - 3M range.
  (setq read-process-output-max (* 1024 1024)) ;; 1mb

  (setq global-mark-ring-max 5000         ; increase mark ring to contains 5000 entries
        mark-ring-max 5000                ; increase kill ring to contains 5000 entries
        mode-require-final-newline t      ; add a newline to end of file
        )

  ;; GROUP: Editing -> Killing
  (setq
   kill-ring-max 5000 ; increase kill-ring capacity
   kill-whole-line t  ; if NIL, kill whole line and move the next line up
   )

#+end_src
* Keep Folders Clean

We use the [[https://github.com/emacscollective/no-littering/blob/master/no-littering.el][no-littering]] package to keep folders where we edit files and the Emacs configuration folder clean!  It knows about a wide variety of variables for built in Emacs features as well as those from community packages so it can be much easier than finding and setting these variables yourself.

#+begin_src emacs-lisp
  ;; NOTE: If you want to move everything out of the ~/.emacs.d folder
  ;; reliably, set `user-emacs-directory` before loading no-littering!
  (setq user-emacs-directory "~/.cache/emacs")

  (use-package no-littering)

  ;; no-littering doesn't set this by default so we must place
  ;; auto save files in the same path as it uses for sessions
  (setq auto-save-file-name-transforms
        `((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))

#+end_src

* Basic UI Configuration

This section configures basic UI settings that remove unneeded elements to make Emacs look a lot more minimal and modern.  If you're just getting started in Emacs, the menu bar might be helpful so you can remove the =(menu-bar-mode -1)= line if you'd like to still see that.

#+begin_src emacs-lisp

  (setq inhibit-startup-message t)

  (scroll-bar-mode -1)        ; Disable visible scrollbar
  (tool-bar-mode -1)          ; Disable the toolbar
  (tooltip-mode -1)           ; Disable tooltips
  (set-fringe-mode 10)        ; Give some breathing room

  (menu-bar-mode -1)            ; Disable the menu bar

  ;; Set up the visible bell
  (setq visible-bell t)

  (column-number-mode)
  (global-display-line-numbers-mode t)

  ;; Set frame transparency
;;  (set-frame-parameter (selected-frame) 'alpha efs/frame-transparency)
;;  (add-to-list 'default-frame-alist `(alpha . ,efs/frame-transparency))
  (set-frame-parameter (selected-frame) 'fullscreen 'maximized)
  (add-to-list 'default-frame-alist '(fullscreen . maximized))

  ;; Disable line numbers for some modes
  (dolist (mode '(org-mode-hook
                  term-mode-hook
                  shell-mode-hook
                  treemacs-mode-hook
                  eshell-mode-hook))
    (add-hook mode (lambda () (display-line-numbers-mode 0))))

#+end_src

** Font Configuration

I am using the [[https://github.com/tonsky/FiraCode][Fira Code]] and [[https://fonts.google.com/specimen/Cantarell][Cantarell]] fonts for this configuration which will more than likely need to be installed on your machine.  Both can usually be found in the various Linux distro package managers or downloaded from the links above.

#+begin_src emacs-lisp

    (set-face-attribute 'default nil :font "Monaco" :height psk/default-font-size
                        :weight 'semi-light)

    ;; Set the fixed pitch face "Fira Code Retina"
    (set-face-attribute 'fixed-pitch nil :font "Monaco" :height psk/default-font-size)

    ;; Set the variable pitch face Cantarell
    (set-face-attribute 'variable-pitch nil :font "Cantarell" :height psk/default-variable-font-size :weight 'regular)

#+end_src

* UI Configuration

** Command Log Mode

[[https://github.com/lewang/command-log-mode][command-log-mode]] is useful for displaying a panel showing each key binding you use in a panel on the right side of the frame.  Great for live streams and screencasts!

#+begin_src emacs-lisp

  (use-package command-log-mode
    :commands command-log-mode)

#+end_src

** Highlight line

#+begin_src emacs-lisp

  (global-hl-line-mode t)

#+end_src

** Color Theme
*** Doom(x)
[[https://github.com/hlissner/emacs-doom-themes][doom-themes]] is a great set of themes with a lot of variety and support for many different Emacs modes.  Taking a look at the [[https://github.com/hlissner/emacs-doom-themes/tree/screenshots][screenshots]] might help you decide which one you like best.  You can also run =M-x counsel-load-theme= to choose between them easily.

#+begin_src emacs-lisp

;;(use-package doom-themes
;;  :init (load-theme 'doom-dark+ t))

#+end_src

*** VS code

#+begin_src emacs-lisp

	;; (use-package solaire-mode
	;; 	:config
	;; 	(solaire-global-mode +1))

	;; ;;
	;; A more complex, more lazy-loaded config
	;; 	(use-package solaire-mode
	;; 		;; Ensure solaire-mode is running in all solaire-mode buffers
	;; 		:hook (change-major-mode . turn-on-solaire-mode)
	;; 		;; ...if you use auto-revert-mode, this prevents solaire-mode from turning
	;; 		;; itself off every time Emacs reverts the file
	;; 		:hook (after-revert . turn-on-solaire-mode)
	;; 		;; To enable solaire-mode unconditionally for certain modes:
	;; 		:hook (ediff-prepare-buffer . solaire-mode)
	;; 		;; Highlight the minibuffer when it is activated:
	;; 		:hook (minibuffer-setup . solaire-mode-in-minibuffer)
	;; 		:config
	;; 		;; The bright and dark background colors are automatically swapped the first
	;; 		;; time solaire-mode is activated. Namely, the backgrounds of the `default` and
	;; 		;; `solaire-default-face` faces are swapped. This is done because the colors
	;; 		;; are usually the wrong way around. If you don't want this, you can disable it:
	;; 		(setq solaire-mode-auto-swap-bg nil)

	;; (setq solaire-mode-remap-modeline nil)

	;; 		(solaire-global-mode +1))

	(use-package vscode-dark-plus-theme
		:config
		(load-theme 'vscode-dark-plus t))

#+end_src

** Better Modeline

[[https://github.com/seagle0128/doom-modeline][doom-modeline]] is a very attractive and rich (yet still minimal) mode line configuration for Emacs.  The default configuration is quite good but you can check out the [[https://github.com/seagle0128/doom-modeline#customize][configuration options]] for more things you can enable or disable.

*NOTE:* The first time you load your configuration on a new machine, you'll need to run `M-x all-the-icons-install-fonts` so that mode line icons display correctly.

#+begin_src emacs-lisp

	(use-package all-the-icons)

	(use-package doom-modeline
		:init (doom-modeline-mode 1)
		:custom ((doom-modeline-height 5))
		:config
		(setq doom-modeline-bar-width 4)

		;; Whether to use hud instead of default bar. It's only respected in GUI.
		;(defcustom doom-modeline-hud 1)

		;; The limit of the window width.
		;; If `window-width' is smaller than the limit, some information won't be displayed.
		(setq doom-modeline-window-width-limit fill-column)

		;; How to detect the project root.
		;; The default priority of detection is `ffip' > `projectile' > `project'.
		;; nil means to use `default-directory'.
		;; The project management packages have some issues on detecting project root.
		;; e.g. `projectile' doesn't handle symlink folders well, while `project' is unable
		;; to hanle sub-projects.
		;; You can specify one if you encounter the issue.
		(setq doom-modeline-project-detection 'project)

		;; Determines the style used by `doom-modeline-buffer-file-name'.
		;;
		;; Given ~/Projects/FOSS/emacs/lisp/comint.el
		;;   auto => emacs/lisp/comint.el (in a project) or comint.el
		;;   truncate-upto-project => ~/P/F/emacs/lisp/comint.el
		;;   truncate-from-project => ~/Projects/FOSS/emacs/l/comint.el
		;;   truncate-with-project => emacs/l/comint.el
		;;   truncate-except-project => ~/P/F/emacs/l/comint.el
		;;   truncate-upto-root => ~/P/F/e/lisp/comint.el
		;;   truncate-all => ~/P/F/e/l/comint.el
		;;   truncate-nil => ~/Projects/FOSS/emacs/lisp/comint.el
		;;   relative-from-project => emacs/lisp/comint.el
		;;   relative-to-project => lisp/comint.el
		;;   file-name => comint.el
		;;   buffer-name => comint.el<2> (uniquify buffer name)
		;;
		;; If you are experiencing the laggy issue, especially while editing remote files
		;; with tramp, please try `file-name' style.
		;; Please refer to https://github.com/bbatsov/projectile/issues/657.
		(setq doom-modeline-buffer-file-name-style 'auto)

		;; Whether display icons in the mode-line.
		;; While using the server mode in GUI, should set the value explicitly.
		(setq doom-modeline-icon (display-graphic-p))

		;; Whether display the icon for `major-mode'. It respects `doom-modeline-icon'.
		(setq doom-modeline-major-mode-icon t)

		;; Whether display the colorful icon for `major-mode'.
		;; It respects `all-the-icons-color-icons'.
		(setq doom-modeline-major-mode-color-icon t)

		;; Whether display the icon for the buffer state. It respects `doom-modeline-icon'.
		(setq doom-modeline-buffer-state-icon t)

		;; Whether display the modification icon for the buffer.
		;; It respects `doom-modeline-icon' and `doom-modeline-buffer-state-icon'.
		(setq doom-modeline-buffer-modification-icon t)

		;; Whether to use unicode as a fallback (instead of ASCII) when not using icons.
		(setq doom-modeline-unicode-fallback nil)

		;; Whether display the minor modes in the mode-line.
		(setq doom-modeline-minor-modes nil)

		;; If non-nil, a word count will be added to the selection-info modeline segment.
		(setq doom-modeline-enable-word-count nil)

		;; Major modes in which to display word count continuously.
		;; Also applies to any derived modes. Respects `doom-modeline-enable-word-count'.
		;; If it brings the sluggish issue, disable `doom-modeline-enable-word-count' or
		;; remove the modes from `doom-modeline-continuous-word-count-modes'.
		(setq doom-modeline-continuous-word-count-modes '(markdown-mode gfm-mode org-mode))

		;; Whether display the buffer encoding.
		(setq doom-modeline-buffer-encoding t)

		;; Whether display the indentation information.
		(setq doom-modeline-indent-info nil)

		;; If non-nil, only display one number for checker information if applicable.
		(setq doom-modeline-checker-simple-format t)

		;; The maximum number displayed for notifications.
		(setq doom-modeline-number-limit 99)

		;; The maximum displayed length of the branch name of version control.
		(setq doom-modeline-vcs-max-length 12)

		;; Whether display the workspace name. Non-nil to display in the mode-line.
		(setq doom-modeline-workspace-name t)

		;; Whether display the perspective name. Non-nil to display in the mode-line.
		(setq doom-modeline-persp-name t)

		;; If non nil the default perspective name is displayed in the mode-line.
		(setq doom-modeline-display-default-persp-name nil)

		;; If non nil the perspective name is displayed alongside a folder icon.
		(setq doom-modeline-persp-icon t)

		;; Whether display the `lsp' state. Non-nil to display in the mode-line.
		(setq doom-modeline-lsp t)

		;; Whether display the GitHub notifications. It requires `ghub' package.
		(setq doom-modeline-github nil)

		;; The interval of checking GitHub.
		(setq doom-modeline-github-interval (* 30 60))

		;; Whether display the modal state icon.
		;; Including `evil', `overwrite', `god', `ryo' and `xah-fly-keys', etc.
		(setq doom-modeline-modal-icon t)

		;; Whether display the gnus notifications.
		(setq doom-modeline-gnus t)

		;; Wheter gnus should automatically be updated and how often (set to 0 or smaller than 0 to disable)
		(setq doom-modeline-gnus-timer 2)

		;; Wheter groups should be excludede when gnus automatically being updated.
		(setq doom-modeline-gnus-excluded-groups '("dummy.group"))

		;; Whether display the IRC notifications. It requires `circe' or `erc' package.
		(setq doom-modeline-irc t)

		;; Function to stylize the irc buffer names.
		(setq doom-modeline-irc-stylize 'identity)

		;; Whether display the environment version.
		(setq doom-modeline-env-version t)
		;; Or for individual languages
		(setq doom-modeline-env-enable-python t)
		(setq doom-modeline-env-enable-ruby t)
		(setq doom-modeline-env-enable-perl t)
		(setq doom-modeline-env-enable-go t)
		(setq doom-modeline-env-enable-elixir t)
		(setq doom-modeline-env-enable-rust t)

		;; Change the executables to use for the language version string
		(setq doom-modeline-env-python-executable "python") ; or `python-shell-interpreter'
		(setq doom-modeline-env-ruby-executable "ruby")
		(setq doom-modeline-env-perl-executable "perl")
		(setq doom-modeline-env-go-executable "go")
		(setq doom-modeline-env-elixir-executable "iex")
		(setq doom-modeline-env-rust-executable "rustc")

		;; What to display as the version while a new one is being loaded
		(setq doom-modeline-env-load-string "...")

		;; Hooks that run before/after the modeline version string is updated
		(setq doom-modeline-before-update-env-hook nil)
		(setq doom-modeline-after-update-env-hook nil))

#+end_src

** Shell

color
#+begin_src emacs-lisp
  (add-hook 'shell-mode-hook
            (lambda ()
              (face-remap-set-base 'comint-highlight-prompt :inherit nil)))
#+end_src

** Which Key

[[https://github.com/justbur/emacs-which-key][which-key]] is a useful UI panel that appears when you start pressing any key binding in Emacs to offer you all possible completions for the prefix.  For example, if you press =C-c= (hold control and press the letter =c=), a panel will appear at the bottom of the frame displaying all of the bindings under that prefix and which command they run.  This is very useful for learning the possible key bindings in the mode of your current buffer.

#+begin_src emacs-lisp

  (use-package which-key
    :defer 0
    :diminish which-key-mode
    :config
    (which-key-mode)
    (setq which-key-idle-delay 1))

#+end_src

** Ivy and Counsel

[[https://oremacs.com/swiper/][Ivy]] is an excellent completion framework for Emacs.  It provides a minimal yet powerful selection menu that appears when you open files, switch buffers, and for many other tasks in Emacs.  Counsel is a customized set of commands to replace `find-file` with `counsel-find-file`, etc which provide useful commands for each of the default completion commands.

[[https://github.com/Yevgnen/ivy-rich][ivy-rich]] adds extra columns to a few of the Counsel commands to provide more information about each item.

#+begin_src emacs-lisp

  (use-package counsel
    :bind (("C-M-j" . 'counsel-switch-buffer)
           :map minibuffer-local-map
           ("C-r" . 'counsel-minibuffer-history))
    :custom
    (counsel-linux-app-format-function #'counsel-linux-app-format-function-name-only)
    :config
    (counsel-mode 1))

#+end_src

** Smart move to beginning of line
- Move point back to indentation of beginning of line. Move point to the first non-whitespace character on this line. If point is already there, move to the beginning of the line. Effectively toggle between the first non-whitespace character and the beginning of the line. If ARG is not nil or 1, move forward ARG - 1 lines first.  If point reaches the beginning or end of the buffer, stop there.
  #+BEGIN_SRC emacs-lisp

    (defun smarter-move-beginning-of-line (arg)
      (interactive "^p")
      (setq arg (or arg 1))

      ;; Move lines first
      (when (/= arg 1)
        (let ((line-move-visual nil))
          (forward-line (1- arg))))

      (let ((orig-point (point)))
        (back-to-indentation)
        (when (= orig-point (point))
          (move-beginning-of-line 1))))

    ;; remap C-a to `smarter-move-beginning-of-line'
    (global-set-key [remap move-beginning-of-line]
                    'smarter-move-beginning-of-line)

  #+END_SRC

** Undo-tree

#+BEGIN_SRC emacs-lisp

  (use-package undo-tree
    :init
    (global-undo-tree-mode))

#+END_SRC
** Highlight
*** Highlight-symbol

#+BEGIN_SRC emacs-lisp

	(use-package highlight-symbol
		:config
		(set-face-attribute 'highlight-symbol-face nil
												:background "default"
												:foreground "#FA009A")
		(setq highlight-symbol-idle-delay 0
					highlight-symbol-on-navigation-p t)
		(add-hook 'prog-mode-hook #'highlight-symbol-mode)
		(add-hook 'prog-mode-hook #'highlight-symbol-nav-mode)
		(global-set-key [(control shift mouse-1)]
										(lambda (event)
											(interactive "e")
											(goto-char (posn-point (event-start event)))
											(highlight-symbol-at-point)))
	;;  (global-set-key [(control f3)] 'highlight-symbol)
		(global-set-key [(meta f3)] 'highlight-symbol-query-replace)
		(global-set-key (kbd "M-n") 'highlight-symbol-next)
		(global-set-key (kbd "M-p") 'highlight-symbol-prev))

#+END_SRC

*** highlight-numbers
#+BEGIN_SRC emacs-lisp

(use-package highlight-numbers
  :config
  (add-hook 'prog-mode-hook 'highlight-numbers-mode))

#+END_SRC

** Helm

*** Helm

#+begin_src emacs-lisp

		(use-package helm
			:diminish
			:bind-keymap
			("C-c h" . helm-command-map)
			:bind (("M-x" . helm-M-x)
						 ("M-y" . helm-show-kill-ring)
						 ("C-x b" . helm-mini)
						 ("C-x C-f" . helm-find-files)
						 ("C-h SPC" . helm-all-mark-rings)
						 :map helm-command-map
						 ("x" . helm-register)
						 ("M-:" . helm-eval-expression-with-eldoc)
						 ("o" . helm-occur)
						 :map helm-map
						 ("C-i" . helm-execute-persistent-action)
						 ("TAB" . helm-execute-persistent-action) ; make TAB work in terminal
						 ("C-z" . helm-select-action) ; list actions using C-z
						 )
			:config
			(setq helm-idle-delay 0.1)
			(setq helm-input-idle-delay 0.1)
			;; The default "C-x c" is quite close to "C-x C-c", which quits Emacs.
			;; Changed to "C-c h". Note: We must set "C-c h" globally, because we
			;; cannot change `helm-command-prefix-key' once `helm-config' is loaded.

			(setq helm-split-window-in-side-p           -1 ; open helm buffer inside current window, not occupy whole other window
						helm-move-to-line-cycle-in-source   t ; move to end or beginning of source when reaching top or bottom of source.
						helm-ff-search-library-in-sexp        t ; search for library in `require' and `declare-function' sexp.
						helm-scroll-amount                    8 ; scroll 8 lines other window using M-<next>/M-<prior>
						helm-ff-file-name-history-use-recentf t
						helm-echo-input-in-header-line t)
			(setq helm-autoresize-max-height 25)
			(setq helm-autoresize-min-height 25)
			;;(setq helm-default-display-buffer-functions '(display-buffer-in-atom-window))
			(setq helm-locate-fuzzy-match t)
			(helm-autoresize-mode 1)
			(helm-mode 1))

		(when (executable-find "ack-grep")
			(setq helm-grep-default-command "ack-grep -Hn --no-group --no-color %e %p %f"
						helm-grep-default-recurse-command "ack-grep -H --no-group --no-color %e %p %f"))

		(setq helm-buffers-fuzzy-matching t
					helm-recentf-fuzzy-match    t
					helm-imenu-fuzzy-match t)

		(setq helm-M-x-fuzzy-match t) ;; optional fuzzy matching for helm-M-x

		(when (executable-find "curl")
			(setq helm-google-suggest-use-curl-p t))

#+end_src

*** helm-ag

#+begin_src emacs-lisp
  (use-package helm-ag
    :after helm
    :config
    (custom-set-variables
     '(helm-ag-base-command "ag --nocolor --nogroup --ignore-case")
     '(helm-ag-command-option "--all-text")
     '(helm-ag-insert-at-point 'symbol)
     '(helm-ag-ignore-buffer-patterns '("\\.txt\\'" "\\.mkd\\'"))))

#+end_src

**** Linux

#+begin_src sh :tangle no

apt install silversearcher-ag

#+end_src

*** helm-swiper

#+begin_src emacs-lisp

  (use-package swiper-helm
    :after helm
;;    :bind (("C-s" . swiper-helm))
    )

#+end_src
*** helm-gtag
#+BEGIN_SRC emacs-lisp

  (use-package helm-gtags
    :config
    (setq
     helm-gtags-ignore-case t
     helm-gtags-auto-update t
     helm-gtags-use-input-at-cursor t
     helm-gtags-pulse-at-cursor t
     helm-gtags-prefix-key "\C-cg"
     helm-gtags-suggested-key-mapping t)
    :config
    (add-hook 'dired-mode-hook 'helm-gtags-mode)
    (add-hook 'eshell-mode-hook 'helm-gtags-mode)
    (add-hook 'c-mode-hook 'helm-gtags-mode)
    (add-hook 'c++-mode-hook 'helm-gtags-mode)
    (add-hook 'asm-mode-hook 'helm-gtags-mode)

    ;;(define-key helm-gtags-mode-map (kbd "C-c g a") 'helm-gtags-tags-in-this-function)
    (define-key helm-gtags-mode-map (kbd "C-j") 'helm-gtags-select)
    (define-key helm-gtags-mode-map (kbd "M-.") 'helm-gtags-dwim)
    ;;(define-key helm-gtags-mode-map (kbd "M-,") 'helm-gtags-pop-stack)
    ;;(define-key helm-gtags-mode-map (kbd "C-c <") 'helm-gtags-previous-history)
    ;;(define-key helm-gtags-mode-map (kbd "C-c >") 'helm-gtags-next-history)
    ;;(define-key helm-gtags-mode-map (kbd "C-c p g") 'helm-gtags-next-history)
    ;;(define-key helm-gtags-mode-map (kbd "C-c g f") 'helm-gtags-find-files)
    )

#+END_SRC

** Helpful Help Commands

[[https://github.com/Wilfred/helpful][Helpful]] adds a lot of very helpful (get it?) information to Emacs' =describe-= command buffers.  For example, if you use =describe-function=, you will not only get the documentation about the function, you will also see the source code of the function and where it gets used in other places in the Emacs configuration.  It is very useful for figuring out how things work in Emacs.

#+begin_src emacs-lisp

  (use-package helpful
    :commands (helpful-callable helpful-variable helpful-command helpful-key)
    :custom
    (counsel-describe-function-function #'helpful-callable)
    (counsel-describe-variable-function #'helpful-variable)
    :bind
    ([remap describe-function] . counsel-describe-function)
    ([remap describe-command] . helpful-command)
    ([remap describe-variable] . counsel-describe-variable)
    ([remap describe-key] . helpful-key))

#+end_src

** Encoding

#+BEGIN_SRC emacs-lisp

  (set-terminal-coding-system 'utf-8)
  (set-keyboard-coding-system 'utf-8)
  (set-language-environment "UTF-8")
  (prefer-coding-system 'utf-8)

  (set-language-environment "Korean")
  (prefer-coding-system 'utf-8)

#+END_SRC

** Adaptive-Wrap
- Show a nice new line

  #+BEGIN_SRC emacs-lisp

    (use-package adaptive-wrap
      :config
      (when (fboundp 'adaptive-wrap-prefix-mode)
        (defun my-activate-adaptive-wrap-prefix-mode ()
          "Toggle `visual-line-mode' and `adaptive-wrap-prefix-mode' simultaneously."
          (adaptive-wrap-prefix-mode (if visual-line-mode 1 -1)))
        (add-hook 'visual-line-mode-hook 'my-activate-adaptive-wrap-prefix-mode)))

  #+END_SRC

** Tabbar (X)

#+begin_src emacs-lisp

	(use-package tabbar
		:disabled
		:config
		(tabbar-mode t))

#+end_src

** Markdown
*** markdown
#+BEGIN_SRC emacs-lisp

  (use-package markdown-mode
    :commands (markdown-mode gfm-mode)
    :mode (("README\\.md\\'" . gfm-mode)
           ("\\.md\\'" . markdown-mode)
           ("\\.markdown\\'" . markdown-mode))
    :init (setq markdown-command "multimarkdown"))

#+END_SRC
*** Flymd
- On the fly markdown preview
**** Link
- [[https://github.com/mola-T/flymd][Homepage]]
  #+BEGIN_SRC emacs-lisp

    (use-package flymd)

  #+END_SRC

** revert
#+BEGIN_SRC emacs-lisp

  (setq save-interprogram-paste-before-kill t)

  ;; update any change made on file to the current buffer
  (global-auto-revert-mode)
  (setq auto-revert-verbose nil)

#+END_SRC

** whitespace
#+BEGIN_SRC emacs-lisp

  (add-hook 'prog-mode-hook (lambda () (interactive) (setq show-trailing-whitespace 1)))
  (define-key prog-mode-map (kbd "C-c w") 'whitespace-mode)
  ;;  (global-set-key (kbd "C-c w") 'whitespace-mode)

#+END_SRC

** savespace
#+begin_src emacs-lisp

  (use-package saveplace
    :config
    (setq-default save-place t)
    (toggle-save-place-globally 1))

#+end_src

** Beacon mode
- flashes the cursor's line when you scroll

#+BEGIN_SRC emacs-lisp
  (use-package beacon
    :config
    (beacon-mode 1)
    ;; this color looks good for the zenburn theme but not for the one
    ;; I'm using for the videos
    ;; (setq beacon-color "#666600")
    )
#+END_SRC

** pretty-mode
#+BEGIN_SRC emacs-lisp
  (when window-system
    (use-package pretty-mode
      :config
      (global-pretty-mode t)))
#+END_SRC
* Development

** Languages

*** IDE Features with lsp-mode

**** lsp-mode

We use the excellent [[https://emacs-lsp.github.io/lsp-mode/][lsp-mode]] to enable IDE-like functionality for many different programming languages via "language servers" that speak the [[https://microsoft.github.io/language-server-protocol/][Language Server Protocol]].  Before trying to set up =lsp-mode= for a particular language, check out the [[https://emacs-lsp.github.io/lsp-mode/page/languages/][documentation for your language]] so that you can learn which language servers are available and how to install them.

The =lsp-keymap-prefix= setting enables you to define a prefix for where =lsp-mode='s default keybindings will be added.  I *highly recommend* using the prefix to find out what you can do with =lsp-mode= in a buffer.

The =which-key= integration adds helpful descriptions of the various keys so you should be able to learn a lot just by pressing =C-c l= in a =lsp-mode= buffer and trying different things that you find there.

#+begin_src emacs-lisp

  (defun efs/lsp-mode-setup ()
    (setq lsp-headerline-breadcrumb-segments '(path-up-to-project file symbols))
    (lsp-headerline-breadcrumb-mode))

  (use-package lsp-mode
    :commands (lsp lsp-deferred)
    :hook (lsp-mode . efs/lsp-mode-setup)
    :init
    (setq lsp-keymap-prefix "C-c l")  ;; Or 'C-l', 's-l'
    :config
    (lsp-enable-which-key-integration t)
    ;; `-background-index' requires clangd v8+!
    ;;(setq lsp-clients-clangd-args '("-j=4" "-background-index" "-log=error"))
    (add-hook 'python-mode-hook #'lsp)
    (add-hook 'rust-mode-hook #'lsp))

  (add-hook 'c-mode-hook 'lsp)
  (add-hook 'c++-mode-hook 'lsp)

#+end_src

***** Reference
+ [[https://www.mortens.dev/blog/emacs-and-the-language-server-protocol/index.html][lsp]]

**** lsp-ui

[[https://emacs-lsp.github.io/lsp-ui/][lsp-ui]] is a set of UI enhancements built on top of =lsp-mode= which make Emacs feel even more like an IDE.  Check out the screenshots on the =lsp-ui= homepage (linked at the beginning of this paragraph) to see examples of what it can do.

#+begin_src emacs-lisp

  (use-package lsp-ui
    :requires lsp-mode flycheck
    :hook (lsp-mode . lsp-ui-mode)
    :custom
    (lsp-ui-doc-position 'bottom)
    (lsp-ui-doc-enable t))
    ;; :config
    ;; (setq lsp-ui-doc-enable t
    ;;       lsp-ui-doc-use-childframe t
    ;;       lsp-ui-doc-include-signature t
    ;;       lsp-ui-sideline-enable t
    ;;       lsp-ui-flycheck-enable t
    ;;       lsp-ui-flycheck-list-position 'right
    ;;       lsp-ui-flycheck-live-reporting t
    ;;       lsp-ui-peek-enable t
    ;;       lsp-ui-peek-list-width 60
    ;;       lsp-ui-peek-peek-height 25))

#+end_src

**** lsp-treemacs

[[https://github.com/emacs-lsp/lsp-treemacs][lsp-treemacs]] provides nice tree views for different aspects of your code like symbols in a file, references of a symbol, or diagnostic messages (errors and warnings) that are found in your code.

Try these commands with =M-x=:

- =lsp-treemacs-symbols= - Show a tree view of the symbols in the current file
- =lsp-treemacs-references= - Show a tree view for the references of the symbol under the cursor
- =lsp-treemacs-error-list= - Show a tree view for the diagnostic messages in the project

This package is built on the [[https://github.com/Alexander-Miller/treemacs][treemacs]] package which might be of some interest to you if you like to have a file browser at the left side of your screen in your editor.

#+begin_src emacs-lisp

	(use-package lsp-treemacs
		:after lsp
		:bind ("C-'" . lsp-treemacs-symbols)
		:config
		(lsp-treemacs-sync-mode 1))
;;		(add-hook 'prog-mode-hook 'lsp-treemacs-symbols))
(define-key prog-mode-map (kbd "C-'") 'lsp-treemacs-symbols)

#+end_src

**** lsp-ivy (X)

[[https://github.com/emacs-lsp/lsp-ivy][lsp-ivy]] integrates Ivy with =lsp-mode= to make it easy to search for things by name in your code.  When you run these commands, a prompt will appear in the minibuffer allowing you to type part of the name of a symbol in your code.  Results will be populated in the minibuffer so that you can find what you're looking for and jump to that location in the code upon selecting the result.

Try these commands with =M-x=:

- =lsp-ivy-workspace-symbol= - Search for a symbol name in the current project workspace
- =lsp-ivy-global-workspace-symbol= - Search for a symbol name in all active project workspaces

#+begin_src emacs-lisp

	(use-package lsp-ivy
		:disabled
		:after lsp)

#+end_src

**** ccls
***** linux
#+begin_src sh
apt install ccls
#+end_src
***** emacs
#+begin_src emacs-lisp :tangle no
  (use-package ccls
    :hook ((c-mode c++-mode objc-mode cuda-mode) .
           (lambda () (require 'ccls) (lsp)))
    :config
    (setq ccls-executable "/usr/bin/ccls")
    (setq ccls-args '("--log-file=/tmp/ccls.log"))
    (setq lsp-perfer-flymake nil))
#+end_src

*** Python

We use =lsp-mode= and =dap-mode= to provide a more complete development environment for Python in Emacs.  Check out [[https://emacs-lsp.github.io/lsp-mode/page/lsp-pyls/][the =pyls= configuration]] in the =lsp-mode= documentation for more details.

Make sure you have the =pyls= language server installed before trying =lsp-mode=!

#+begin_src sh :tangle no

pip install --user "python-language-server[all]"

#+end_src

There are a number of other language servers for Python so if you find that =pyls= doesn't work for you, consult the =lsp-mode= [[https://emacs-lsp.github.io/lsp-mode/page/languages/][language configuration documentation]] to try the others!

#+begin_src emacs-lisp

  (use-package python-mode
    :hook (python-mode . lsp-deferred)
    :custom
    ;; NOTE: Set these if Python 3 is called "python3" on your system!
    (python-shell-interpreter "python3")
    (dap-python-executable "python3")
    (dap-python-debugger 'debugpy)
    :config
    (require 'dap-python))


#+end_src

You can use the pyvenv package to use =virtualenv= environments in Emacs.  The =pyvenv-activate= command should configure Emacs to cause =lsp-mode= and =dap-mode= to use the virtual environment when they are loaded, just select the path to your virtual environment before loading your project.

#+begin_src emacs-lisp

  (use-package pyvenv
    :after python-mode
    :config
    (pyvenv-mode 1))

#+end_src

**** lsp
***** lsp-jedi
#+begin_src emacs-lisp :tangle no
(use-package lsp-jedi
  :config
  (with-eval-after-load "lsp-mode"
    (add-to-list 'lsp-disabled-clients 'pyls)
    (add-to-list 'lsp-enabled-clients 'jedi)))
#+end_src

***** jedi language server
#+begin_src sh
pip install -U jedi-language-server
#+end_src

*** Clojure
#+begin_src emacs-lisp
  (use-package cider
    :ensure t)
#+end_src

** Style

#+begin_src emacs-lisp

  (add-hook 'prog-mode-hook (lambda () (interactive) (setq show-trailing-whitespace 1)))
  (delete-selection-mode)

  ;; set appearance of a tab that is represented by 4 spaces
  (setq c-default-style "linux") ; set style to "linux"
  ;;      c-basic-offset 4)
  (setq-default c-basic-offset 2
                tab-width 2
                indent-tabs-mode t)

#+end_src

** Company Mode

[[http://company-mode.github.io/][Company Mode]] provides a nicer in-buffer completion interface than =completion-at-point= which is more reminiscent of what you would expect from an IDE.  We add a simple configuration to make the keybindings a little more useful (=TAB= now completes the selection and initiates completion at the current location if needed).

We also use [[https://github.com/sebastiencs/company-box][company-box]] to further enhance the look of the completions with icons and better overall presentation.

#+begin_src emacs-lisp

  (use-package company
    :after lsp-mode
    :hook (lsp-mode . company-mode)
    :bind (:map company-active-map
                ("C-o" . company-complete-selection))
    (:map lsp-mode-map
          ("C-o" . company-indent-or-complete-common))
    :custom
    (company-minimum-prefix-length 1)
    (company-idle-delay 0.0)
    :config
    (setq lsp-completion-provider :capf))

  ;; (use-package company-lsp
  ;;   :requires company
  ;;   :config
  ;;   (push 'company-lsp company-backends)

  ;;   ;; Disable client-side cache because the LSP server does a better job.
  ;;   (setq company-transformers nil
  ;;         company-lsp-async t
  ;;         company-lsp-cache-candidates nil))

  ;; (use-package company-box
  ;;   :hook (company-mode . company-box-mode))

#+end_src

** Projectile

[[https://projectile.mx/][Projectile]] is a project management library for Emacs which makes it a lot easier to navigate around code projects for various languages.  Many packages integrate with Projectile so it's a good idea to have it installed even if you don't use its commands directly.

#+begin_src emacs-lisp

  (use-package projectile
    :diminish projectile-mode
    :config (projectile-mode)
    :custom ((projectile-completion-system 'helm)
             (projectile-enable-caching t)
             (projectile-indexing-method 'alien))
    :bind-keymap
    ("C-c p" . projectile-command-map)
    :init
    ;; NOTE: Set this to the folder where you keep your Git repos!
    (when (file-directory-p "~/ext/WORKSPACE/")
      (setq projectile-project-search-path '("~/ext/WORKSPACE/")))
    (setq projectile-switch-project-action #'projectile-dired))

  (use-package helm-projectile
    :after projectile
    :config
    (helm-projectile-on)
    (setq projectile-switch-project-action 'helm-projectile))

#+end_src

** Magit

[[https://magit.vc/][Magit]] is the best Git interface I've ever used.  Common Git operations are easy to execute quickly using Magit's command panel system.

#+begin_src emacs-lisp

  (use-package magit
    :commands magit-status
    :custom
    (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))

  ;; NOTE: Make sure to configure a GitHub token before using this package!
  ;; - https://magit.vc/manual/forge/Token-Creation.html#Token-Creation
  ;; - https://magit.vc/manual/ghub/Getting-Started.html#Getting-Started
  (use-package forge
    :after magit)

#+end_src


** Yasnippet
#+begin_src emacs-lisp

  (use-package yasnippet
    :config
    (yas-global-mode 1))

#+end_src

*** snipepets

#+begin_src emacs-lisp

  (use-package yasnippet-snippets
    :after yasnippet)

#+end_src
** Rainbow Delimiters

[[https://github.com/Fanael/rainbow-delimiters][rainbow-delimiters]] is useful in programming modes because it colorizes nested parentheses and brackets according to their nesting depth.  This makes it a lot easier to visually match parentheses in Emacs Lisp code without having to count them yourself.

#+begin_src emacs-lisp

(use-package rainbow-delimiters
  :hook (prog-mode . rainbow-delimiters-mode))

#+end_src
** Compile

#+BEGIN_SRC emacs-lisp
  
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;; GROUP: Programming -> Tools -> Compilation ;;
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;; Compilation from Emacs
  (defun prelude-colorize-compilation-buffer ()
    "Colorize a compilation mode buffer."
    (interactive)
    ;; we don't want to mess with child modes such as grep-mode, ack, ag, etc
    (when (eq major-mode 'compilation-mode)
      (let ((inhibit-read-only t))
        (ansi-color-apply-on-region (point-min) (point-max)))))
  
  ;; setup compilation-mode used by `compile' command
  ;; 	(defun kps/my_compile_path ()
  ;; (interactive)
  ;; 		(defvar kps/cur_path (projectile-project-root))
  ;; ;;		(setq compile-command kps/cur_path)
  ;; 		(compile 'kps/cur_path)
  ;; 		)
  
  (defun kps/compile-next-makefile ()
    (interactive)
    (let* ((compile-command (concat (projectile-project-root) "os/dbuild.sh")))
      (compile compile-command)))
  
  (use-package compile
    :config
    (setq compilation-ask-about-save nil          ; Just save before compiling
          compilation-always-kill t               ; Just kill old compile processes before starting the new one
          compilation-scroll-output 'first-error) ; Automatically scroll to first
    ;;(define-key prog-mode-map (kbd "<C-f5>") 'kps/compile-next-makefile)
    )
  
  (defun pk/compile (idx)
    (let (command)
      (if (eq idx 1)
          (setq command (concat (projectile-project-root) "os/dbuild.sh"))
        (if (eq idx 2)
            (setq command (concat (projectile-project-root) "os/dbuild.sh download os"))
          (if (eq idx 3)
              (setq command (concat (projectile-project-root) "os/dbuild.sh clean"))
            (if (eq idx 5)
                (setq command (concat (projectile-project-root) "os/dbuild.sh"  " && " (projectile-project-root) "os/dbuild.sh download os"))
              (if (eq idx 6)
                  (setq command (concat (projectile-project-root) "os/dbuild.sh"  " && " (projectile-project-root) "os/dbuild.sh download all"))
                (if (eq idx 4)
                    (setq command (concat (projectile-project-root) "os/dbuild.sh download all")))
                )))))
      (setq-local compile-command command))
    (setq-local compilation-read-command nil)
    (call-interactively 'compile))
  
  (define-key prog-mode-map
    (kbd "<C-f5>")
    (lambda ()
      (interactive)
      (let (n)
        (setq n (read-number "option build(1) download(2) clean(3) all(4) bdos(5) bdall(6): " 1))
        (pk/compile n))))
#+END_SRC

** Makefile

#+BEGIN_SRC emacs-lisp
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;;
  ;; GROUP: Programming -> Tools -> Makefile
  ;; takenn from prelude-c.el:48: https://github.com/bbatsov/prelude/blob/master/modules/prelude-c.el
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  (defun prelude-makefile-mode-defaults ()
    (whitespace-toggle-options '(tabs))
    (setq indent-tabs-mode t))

  (setq prelude-makefile-mode-hook 'prelude-makefile-mode-defaults)

  (add-hook 'makefile-mode-hook (lambda ()
                                  (run-hooks 'prelude-makefile-mode-hook)))

  ;; GROUP: Programming -> Tools -> Ediff
  (setq ediff-diff-options "-w"
        ediff-split-window-function 'split-window-horizontally
        ediff-window-setup-function 'ediff-setup-windows-plain)

#+END_SRC

** GDB

#+BEGIN_SRC emacs-lisp

  (setq gdb-many-windows t      ; use gdb-many-windows by default
        gdb-show-main t)        ; Non-nil means display source file containing the main routine at startup

  (setq gud-chdir-before-run nil)

#+END_SRC


** iedit

#+begin_src emacs-lisp

  (use-package iedit)

  ;; if you're windened, narrow to the region, if you're narrowed, widen
  ;; bound to C-x n
  (defun narrow-or-widen-dwim (p)
    "If the buffer is narrowed, it widens. Otherwise, it narrows intelligently.
    Intelligently means: region, org-src-block, org-subtree, or defun,
    whichever applies first.
    Narrowing to org-src-block actually calls `org-edit-src-code'.

    With prefix P, don't widen, just narrow even if buffer is already
    narrowed."
    (interactive "P")
    (declare (interactive-only))
    (cond ((and (buffer-narrowed-p) (not p)) (widen))
          ((region-active-p)
           (narrow-to-region (region-beginning) (region-end)))
          ((derived-mode-p 'org-mode)
           ;; `org-edit-src-code' is not a real narrowing command.
           ;; Remove this first conditional if you don't want it.
           (cond ((ignore-errors (org-edit-src-code))
                  (delete-other-windows))
                 ((org-at-block-p)
                  (org-narrow-to-block))
                 (t (org-narrow-to-subtree))))
          (t (narrow-to-defun))))

  ;; (define-key endless/toggle-map "n" #'narrow-or-widen-dwim)
  ;; This line actually replaces Emacs' entire narrowing keymap, that's
  ;; how much I like this command. Only copy it if that's what you want.
  (define-key ctl-x-map "n" #'narrow-or-widen-dwim)

  (defun iedit-dwim (arg)
    "Starts iedit but uses \\[narrow-to-defun] to limit its scope."
    (interactive "P")
    (if arg
        (iedit-mode)
      (save-excursion
        (save-restriction
          (widen)
          ;; this function determines the scope of `iedit-start'.
          (if iedit-mode
              (iedit-done)
            ;; `current-word' can of course be replaced by other
            ;; functions.
            (narrow-to-defun)
            (iedit-start (current-word) (point-min) (point-max)))))))

#+end_src

** Kconfig mode

#+BEGIN_SRC emacs-lisp
  ;;; kconfig.el - a major mode for editing linux kernel config (Kconfig) files
  ;; Copyright © 2014 Yu Peng
  ;; Copyright © 2014 Michal Sojka

  (defvar kconfig-mode-font-lock-keywords
    '(("^[\t, ]*\\_<bool\\_>" . font-lock-type-face)
      ("^[\t, ]*\\_<int\\_>" . font-lock-type-face)
      ("^[\t, ]*\\_<boolean\\_>" . font-lock-type-face)
      ("^[\t, ]*\\_<tristate\\_>" . font-lock-type-face)
      ("^[\t, ]*\\_<depends on\\_>" . font-lock-variable-name-face)
      ("^[\t, ]*\\_<select\\_>" . font-lock-variable-name-face)
      ("^[\t, ]*\\_<help\\_>" . font-lock-variable-name-face)
      ("^[\t, ]*\\_<---help---\\_>" . font-lock-variable-name-face)
      ("^[\t, ]*\\_<default\\_>" . font-lock-variable-name-face)
      ("^[\t, ]*\\_<range\\_>" . font-lock-variable-name-face)
      ("^\\_<config\\_>" . font-lock-constant-face)
      ("^\\_<comment\\_>" . font-lock-constant-face)
      ("^\\_<menu\\_>" . font-lock-constant-face)
      ("^\\_<endmenu\\_>" . font-lock-constant-face)
      ("^\\_<if\\_>" . font-lock-constant-face)
      ("^\\_<endif\\_>" . font-lock-constant-face)
      ("^\\_<menuconfig\\_>" . font-lock-constant-face)
      ("^\\_<source\\_>" . font-lock-keyword-face)
      ("\#.*" . font-lock-comment-face)
      ("\".*\"$" . font-lock-string-face)))

  (defvar kconfig-headings
    '("bool" "int" "boolean" "tristate" "depends on" "select"
      "help" "---help---" "default" "range" "config" "comment"
      "menu" "endmenu" "if" "endif" "menuconfig" "source"))

  (defun kconfig-outline-level ()
    (looking-at "[\t ]*")
    (let ((prefix (match-string 0))
          (result 0))
      (dotimes (i (length prefix) result)
        (setq result (+ result
                        (if (equal (elt prefix i) ?\s)
                            1 tab-width))))))

  (define-derived-mode kconfig-mode text-mode
    "kconfig"
    (set (make-local-variable 'font-lock-defaults)
         '(kconfig-mode-font-lock-keywords t))
    (set (make-local-variable 'outline-regexp)
         (concat "^[\t ]*" (regexp-opt kconfig-headings)))
    (set (make-local-variable 'outline-level)
         'kconfig-outline-level))

  (add-to-list 'auto-mode-alist '("Kconfig" . kconfig-mode))
#+END_SRC

* Edit
** avy
- avy is a GNU Emacs package for jumping to visible text using a char-based decision tree. See also ace-jump-mode and vim-easymotion avy uses the same idea.
- I don't need to use arrow key anymore. I can move to where I want to go by this application.

#+BEGIN_SRC emacs-lisp
  (use-package avy
    :bind ("C-c m" . avy-goto-char))
#+END_SRC

** Ace-windows

#+BEGIN_SRC emacs-lisp

  (use-package ace-window
    :init
    (progn
      (global-set-key [remap other-window] 'ace-window)
      (custom-set-faces
       '(aw-leading-char-face
         ((t (:inherit ace-jump-face-foreground :height 3.0)))))))

  (defun pk/swap-windows ()
    "Swap windows"
    (interactive)
    (ace-swap-window)
    (aw-flip-window))

  (defun pk/my-windows ()
    "Go to ilist"
    (interactive)
    (print (buffer-name))
    (ace-window 1))

  ;;(buffer-name)
  (global-set-key (kbd "C-x m") 'pk/swap-windows)

#+END_SRC

** Smartparens
- [[https://github.com/Fuco1/smartparens][Homepage]]
*** Usage
#+BEGIN_SRC emacs-lisp

  (use-package smartparens
    :config
    (setq sp-base-key-bindings 'paredit)
    (setq sp-autoskip-closing-pair 'always)
    (setq sp-hybrid-kill-entire-symbol nil)
    (sp-use-paredit-bindings)
    (show-smartparens-global-mode +1)
    (smartparens-global-mode 1)
    ;; when you press RET, the curly braces automatically
    ;; add another newline
    (sp-with-modes '(c-mode c++-mode)
           (sp-local-pair "{" nil :post-handlers '(("||\n[i]" "RET")))
           (sp-local-pair "/*" "*/" :post-handlers '((" | " "SPC")
                                 ("* ||\n[i]" "RET")))))

#+END_SRC

** Multiple-Cursor

#+BEGIN_SRC emacs-lisp

  (use-package multiple-cursors
    :config
    (when (fboundp 'mc/edit-lines)
      (global-set-key (kbd "C-S-c C-S-c") 'mc/edit-lines)
      ;;(global-set-key (kbd "C->") 'mc/mark-next-like-this)
      (global-set-key (kbd "C->") 'mc/mark-next-like-this-word)
      (global-set-key (kbd "C-<") 'mc/mark-previous-like-this)
      (global-set-key (kbd "C-c C-<") 'mc/mark-all-like-this)
      )
    (define-key global-map (kbd "H-%") 'mqr-query-replace)
    (define-key global-map (kbd "H-#") 'mqr-query-replace-regexp))

#+END_SRC

** Macro

#+BEGIN_SRC emacs-lisp

  (global-set-key (kbd "<C-f3>") 'kmacro-start-macro-or-insert-counter)
  (global-set-key (kbd "<f3>") 'kmacro-end-and-call-macro)

#+END_SRC

** Hungry delete mode
- Delete all the whitespace when you hit backspace or delete

#+BEGIN_SRC emacs-lisp

(use-package hungry-delete
    :config
    (global-hungry-delete-mode))

#+END_SRC

** Expand Region

#+BEGIN_SRC emacs-lisp

  (use-package expand-region
    :config
    (global-set-key (kbd "C-=") 'er/expand-region);
    (global-set-key (kbd "C-c b") 'er/contract-region))

#+END_SRC

** hangul

#+begin_src emacs-lisp

(set-fontset-font t 'hangul (font-spec :name "NanumMyeongjo" :weight 'bold :height 180))

#+end_src

** wgrep

#+BEGIN_SRC emacs-lisp
  (use-package wgrep
    :config
    ;;버퍼를 자동으로 저장
    (setq wgrep-auto-save-buffer t)
    ;;키 바인딩?
    (setq wgrep-enable-key "r")
    ;;읽기전용 버퍼 수정
    (setq wgrep-change-readonly-file t))
#+END_SRC

** clean-aindent-mode

#+begin_src emacs-lisp

	(defun my-pkg-init()
		(electric-indent-mode nil)  ; no electric indent, auto-indent is sufficient
		(clean-aindent-mode t)
		(setq clean-aindent-is-simple-indent t)
		(define-key global-map (kbd "RET") 'newline-and-indent))

	(use-package clean-aindent-mode
		:config
		(add-hook 'after-init-hook 'my-pkg-init))

	(use-package dtrt-indent
		:disabled
		:config
		(dtrt-indent-mode 1))

#+end_src

** Diff
*** diff-hl
#+BEGIN_SRC emacs-lisp

  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;; PACKAGE: diff-hl                             ;;
  ;;                                              ;;
  ;; GROUP: Programming -> Tools -> Vc -> Diff Hl ;;
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  (use-package diff-hl
    :after magit
    :config
    (global-diff-hl-mode)
    (add-hook 'dired-mode-hook 'diff-hl-dired-mode)
    (add-hook 'magit-pre-refresh-hook 'diff-hl-magit-pre-refresh)
    (add-hook 'magit-post-refresh-hook 'diff-hl-magit-post-refresh)
    )

  ;; show important whitespace in diff-mode
  (add-hook 'diff-mode-hook (lambda ()
                              (setq-local whitespace-style
                                          '(face
                                            tabs
                                            tab-mark
                                            spaces
                                            space-mark
                                            trailing
                                            indentation::space
                                            indentation::tab
                                            newline
                                            newline-mark))
                              (whitespace-mode 1)))

#+END_SRC

** Macro
*** Basics
- https://www.gnu.org/software/emacs/manual/html_node/emacs/Keyboard-Macros.html#Keyboard-Macros
- http://ergoemacs.org/emacs/emacs_macro_example.html
- http://emacs-fu.blogspot.com/2010/07/keyboard-macros.html
  |--------------------------------------+-----------------------|
  | kmacro-start-macro-or-insert-counter | start recording macro |
  | kmacro-end-and-call-macro            | stop recording macro  |
  | kmacro-name-last-macro               |                       |
  | insert-kbd-macro                     |                       |
  |--------------------------------------+-----------------------|

*** Key bindings
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "<C-f3>") 'kmacro-start-macro-or-insert-counter)
  (global-set-key (kbd "<f3>") 'kmacro-end-and-call-macro)
#+END_SRC
* Files
#+begin_src emacs-lisp

  (setq large-file-warning-threshold 100000000) ;; size in bytes

  (add-hook 'dired-mode-hook 'auto-revert-mode)

  (setq dired-listing-switches "-lha --group-directories-first")


  (if (not (file-exists-p backup-directory))
      (make-directory backup-directory t))
  (setq
   make-backup-files t        ; backup a file the first time it is saved
   backup-directory-alist `((".*" . ,backup-directory)) ; save backup files in ~/.backups
   backup-by-copying t     ; copy the current file into backup directory
   version-control t   ; version numbers for backup files
   delete-old-versions t   ; delete unnecessary versions
   kept-old-versions 6     ; oldest versions to keep when a new numbered backup is made (default: 2)
   kept-new-versions 9 ; newest versions to keep when a new numbered backup is made (default: 2)
   auto-save-default t ; auto-save every buffer that visits a file
   auto-save-timeout 20 ; number of seconds idle time before auto-save (default: 30)
   auto-save-interval 200 ; number of keystrokes between auto-saves (default: 300)
   )
#+end_src

** Get Current file path

#+BEGIN_SRC emacs-lisp

  (defun buffer-kill-path ()
    "copy buffer's full path to kill ring"
    (interactive)
    (kill-new (buffer-file-name)))

  ;;  (define-key c++-mode-map (kbd "C-c C-f") 'buffer-kill-path)
  (define-key global-map (kbd "C-c C-f") 'buffer-kill-path)

#+END_SRC

* Utility
** flyspell
#+BEGIN_SRC emacs-lisp

  ;; GROUP: Processes -> Flyspell
  (if (executable-find "aspell")
      (progn
        (setq ispell-program-name "aspell")
        ;;(setq ispell-extra-args '("--sug-mode=ultra"))
        )
    (setq ispell-program-name "ispell"))

  ;(add-hook 'text-mode-hook 'flyspell-mode)
  (add-hook 'org-mode-hook 'flyspell-mode)
  ;(add-hook 'prog-mode-hook 'flyspell-prog-mode)

#+END_SRC
* Org Mode

[[https://orgmode.org/][Org Mode]] is one of the hallmark features of Emacs.  It is a rich document editor, project planner, task and time tracker, blogging engine, and literate coding utility all wrapped up in one package.

** Better Font Faces

The =efs/org-font-setup= function configures various text faces to tweak the sizes of headings and use variable width fonts in most cases so that it looks more like we're editing a document in =org-mode=.  We switch back to fixed width (monospace) fonts for code blocks and tables so that they display correctly.

#+begin_src emacs-lisp

  (defun efs/org-font-setup ()
    ;; Replace list hyphen with dot
    (font-lock-add-keywords 'org-mode
                            '(("^ *\\([-]\\) "
                               (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))

    ;; Set faces for heading levels
    (dolist (face '((org-level-1 . 1.2)
                    (org-level-2 . 1.1)
                    (org-level-3 . 1.05)
                    (org-level-4 . 1.0)
                    (org-level-5 . 1.1)
                    (org-level-6 . 1.1)
                    (org-level-7 . 1.1)
                    (org-level-8 . 1.1)))
      (set-face-attribute (car face) nil :font "Cantarell" :weight 'regular :height (cdr face)))

    ;; Ensure that anything that should be fixed-pitch in Org files appears that way
    (set-face-attribute 'org-block nil    :foreground nil :inherit 'fixed-pitch)
    (set-face-attribute 'org-table nil    :inherit 'fixed-pitch)
    (set-face-attribute 'org-formula nil  :inherit 'fixed-pitch)
    (set-face-attribute 'org-code nil     :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-table nil    :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-verbatim nil :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-special-keyword nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-meta-line nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-checkbox nil  :inherit 'fixed-pitch)
    (set-face-attribute 'line-number nil :inherit 'fixed-pitch)
    (set-face-attribute 'line-number-current-line nil :inherit 'fixed-pitch))

#+end_src

** Fonts
#+begin_src sh :tangle no
	apt install fonts-cantarell
	apt install fonts-firacode
#+end_src

** Basic Config

This section contains the basic configuration for =org-mode= plus the configuration for Org agendas and capture templates.  There's a lot to unpack in here so I'd recommend watching the videos for [[https://youtu.be/VcgjTEa0kU4][Part 5]] and [[https://youtu.be/PNE-mgkZ6HM][Part 6]] for a full explanation.

#+begin_src emacs-lisp

	(defun efs/org-mode-setup ()
		(org-indent-mode)
		(variable-pitch-mode 1)
		(visual-line-mode 1))

	(use-package org
		:pin org
		:commands (org-capture org-agenda)
		:hook (org-mode . efs/org-mode-setup)
		:config
		(setq org-ellipsis " ▾")

		(setq org-agenda-start-with-log-mode t)
		(setq org-log-done 'time)
		(setq org-log-into-drawer t)

		(setq org-agenda-files
					'(psk/task_file_path
						psk/habit_file_path
						psk/birthday_file_path))

		(require 'org-habit)
		(add-to-list 'org-modules 'org-habit)
		(setq org-habit-graph-column 60)

		(setq org-todo-keywords
					'((sequence "TODO(t)" "NEXT(n)" "|" "DONE(d!)")
						(sequence "BACKLOG(b)" "PLAN(p)" "READY(r)" "ACTIVE(a)" "REVIEW(v)" "WAIT(w@/!)" "HOLD(h)" "|" "COMPLETED(c)" "CANC(k@)")))

		(setq org-refile-targets
					'(("Archive.org" :maxlevel . 1)
						("Tasks.org" :maxlevel . 1)))

		;; Save Org buffers after refiling!
		(advice-add 'org-refile :after 'org-save-all-org-buffers)

		(setq org-tag-alist
					'((:startgroup)
																					; Put mutually exclusive tags here
						(:endgroup)
						("@errand" . ?E)
						("@home" . ?H)
						("@work" . ?W)
						("agenda" . ?a)
						("planning" . ?p)
						("publish" . ?P)
						("batch" . ?b)
						("note" . ?n)
						("idea" . ?i)))

		;; Configure custom agenda views
		(setq org-agenda-custom-commands
					'(("d" "Dashboard"
						 ((agenda "" ((org-deadline-warning-days 7)))
							(todo "NEXT"
										((org-agenda-overriding-header "Next Tasks")))
							(tags-todo "agenda/ACTIVE" ((org-agenda-overriding-header "Active Projects")))))

						("n" "Next Tasks"
						 ((todo "NEXT"
										((org-agenda-overriding-header "Next Tasks")))))

						("W" "Work Tasks" tags-todo "+work-email")

						;; Low-effort next actions
						("e" tags-todo "+TODO=\"NEXT\"+Effort<15&+Effort>0"
						 ((org-agenda-overriding-header "Low Effort Tasks")
							(org-agenda-max-todos 20)
							(org-agenda-files org-agenda-files)))

						("w" "Workflow Status"
						 ((todo "WAIT"
										((org-agenda-overriding-header "Waiting on External")
										 (org-agenda-files org-agenda-files)))
							(todo "REVIEW"
										((org-agenda-overriding-header "In Review")
										 (org-agenda-files org-agenda-files)))
							(todo "PLAN"
										((org-agenda-overriding-header "In Planning")
										 (org-agenda-todo-list-sublevels nil)
										 (org-agenda-files org-agenda-files)))
							(todo "BACKLOG"
										((org-agenda-overriding-header "Project Backlog")
										 (org-agenda-todo-list-sublevels nil)
										 (org-agenda-files org-agenda-files)))
							(todo "READY"
										((org-agenda-overriding-header "Ready for Work")
										 (org-agenda-files org-agenda-files)))
							(todo "ACTIVE"
										((org-agenda-overriding-header "Active Projects")
										 (org-agenda-files org-agenda-files)))
							(todo "COMPLETED"
										((org-agenda-overriding-header "Completed Projects")
										 (org-agenda-files org-agenda-files)))
							(todo "CANC"
										((org-agenda-overriding-header "Cancelled Projects")
										 (org-agenda-files org-agenda-files)))))))

		(setq org-capture-templates
					`(("t" "Tasks / Projects")
						("tt" "Task" entry (file+olp "~/Projects/Code/emacs-from-scratch/OrgFiles/Tasks.org" "Inbox")
						 "* TODO %?\n  %U\n  %a\n  %i" :empty-lines 1)

						("j" "Journal Entries")
						("jj" "Journal" entry
						 (file+olp+datetree "~/Projects/Code/emacs-from-scratch/OrgFiles/Journal.org")
						 "\n* %<%I:%M %p> - Journal :journal:\n\n%?\n\n"
						 ;; ,(dw/read-file-as-string "~/Notes/Templates/Daily.org")
						 :clock-in :clock-resume
						 :empty-lines 1)
						("jm" "Meeting" entry
						 (file+olp+datetree "~/Projects/Code/emacs-from-scratch/OrgFiles/Journal.org")
						 "* %<%I:%M %p> - %a :meetings:\n\n%?\n\n"
						 :clock-in :clock-resume
						 :empty-lines 1)

						("w" "Workflows")
						("we" "Checking Email" entry (file+olp+datetree "~/Projects/Code/emacs-from-scratch/OrgFiles/Journal.org")
						 "* Checking Email :email:\n\n%?" :clock-in :clock-resume :empty-lines 1)

						("m" "Metrics Capture")
						("mw" "Weight" table-line (file+headline "~/Projects/Code/emacs-from-scratch/OrgFiles/Metrics.org" "Weight")
						 "| %U | %^{Weight} | %^{Notes} |" :kill-buffer t)))

		(define-key global-map (kbd "C-c j")
			(lambda () (interactive) (org-capture nil "jj")))

		(efs/org-font-setup))

#+end_src

*** Nicer Heading Bullets

[[https://github.com/sabof/org-bullets][org-bullets]] replaces the heading stars in =org-mode= buffers with nicer looking characters that you can control.  Another option for this is [[https://github.com/integral-dw/org-superstar-mode][org-superstar-mode]] which we may cover in a later video.

#+begin_src emacs-lisp

  (use-package org-bullets
    :hook (org-mode . org-bullets-mode)
    :custom
    (org-bullets-bullet-list '("◉" "○" "●" "○" "●" "○" "●")))

#+end_src

*** Center Org Buffers

We use [[https://github.com/joostkremers/visual-fill-column][visual-fill-column]] to center =org-mode= buffers for a more pleasing writing experience as it centers the contents of the buffer horizontally to seem more like you are editing a document.  This is really a matter of personal preference so you can remove the block below if you don't like the behavior.

#+begin_src emacs-lisp

  (defun efs/org-mode-visual-fill ()
    (setq visual-fill-column-width 100
          visual-fill-column-center-text t)
    (visual-fill-column-mode 1))

  (use-package visual-fill-column
    :hook (org-mode . efs/org-mode-visual-fill))

#+end_src

** Configure Babel Languages

To execute or export code in =org-mode= code blocks, you'll need to set up =org-babel-load-languages= for each language you'd like to use.  [[https://orgmode.org/worg/org-contrib/babel/languages.html][This page]] documents all of the languages that you can use with =org-babel=.

#+begin_src emacs-lisp

  (with-eval-after-load 'org
    (org-babel-do-load-languages
        'org-babel-load-languages
        '((emacs-lisp . t)
        (python . t)))

    (push '("conf-unix" . conf-unix) org-src-lang-modes))

#+end_src

** Structure Templates

Org Mode's [[https://orgmode.org/manual/Structure-Templates.html][structure templates]] feature enables you to quickly insert code blocks into your Org files in combination with =org-tempo= by typing =<= followed by the template name like =el= or =py= and then press =TAB=.  For example, to insert an empty =emacs-lisp= block below, you can type =<el= and press =TAB= to expand into such a block.

You can add more =src= block templates below by copying one of the lines and changing the two strings at the end, the first to be the template name and the second to contain the name of the language [[https://orgmode.org/worg/org-contrib/babel/languages.html][as it is known by Org Babel]].

#+begin_src emacs-lisp

  (with-eval-after-load 'org
    ;; This is needed as of Org 9.2
    (require 'org-tempo)

    (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
    (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
    (add-to-list 'org-structure-template-alist '("py" . "src python")))

#+end_src

** Auto-tangle Configuration Files

This snippet adds a hook to =org-mode= buffers so that =efs/org-babel-tangle-config= gets executed each time such a buffer gets saved.  This function checks to see if the file being saved is the Emacs.org file you're looking at right now, and if so, automatically exports the configuration here to the associated output files.

#+begin_src emacs-lisp

  ;; Automatically tangle our Emacs.org config file when we save it
  (defun efs/org-babel-tangle-config ()
    (when (string-equal (file-name-directory (buffer-file-name))
                        (expand-file-name user-emacs-directory))
      ;; Dynamic scoping to the rescue
      (let ((org-confirm-babel-evaluate nil))
        (org-babel-tangle))))

  (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'efs/org-babel-tangle-config)))

#+end_src

** Add org-babel-execute function

By default, only 'emacs-lisp' is enabled for evaluation. To enable or disable other languages, customize the 'org-babel-load-languages' variable either through the emacs customization interface or by adding code to the init file.

#+begin_src emacs-lisp
  (org-babel-do-load-languages
   'org-babel-load-languages '((ditaa . t)))
#+end_src

* Runtime Performance

Dial the GC threshold back down so that garbage collection happens more frequently but in less time.

#+begin_src emacs-lisp

  ;; Make gc pauses faster by decreasing the threshold.
;;  (setq gc-cons-threshold (* 2 1000 1000))

#+end_src

* Emacs Server

Run emacs on daemon. It'll faster opening performance of emacs. Furthermore it shares all files in one emacs, I don't need to worry about to conflict.

** Client Environment

Client name is emacsclient. It runs on terminal environment by default. So I need to add options to run it on GUI. Moreover it doesn't 

/usr/share/applications/emacs24.desktop like this
#+begin_src text :tangle no
  
  TryExec=/usr/bin/emacsclient -c
  Exec=/usr/bin/emacsclient -c %F
#+end_src

** Run server daemon on log in.
#+begin_src emacs-lisp
  (ignore-errors
    (let ((warning-minimum-level :emergency)) ; a kinda tricky way to suppress warning
    (use-package server
    :config
    (unless (server-running-p) (server-start))
    )))
#+end_src

* Terminal

** eterm-256color
#+begin_src emacs-lisp
  (use-package eterm-256color
    :ensure t
    :config
    (add-hook 'term-mode-hook #'eterm-256color-mode))
#+end_src

* ditaa
#+begin_src emacs-lisp 
  (setq org-ditaa-jar-path "/usr/share/ditaa/ditaa.jar")
#+end_src

